<template>
  <div class="home-page">
    <div v-if="isLoading" class="loading-outer">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-linecap="round" fill="none" stroke-dasharray="50.26548245743669 50.26548245743669" stroke="#e15b64" stroke-width="8" r="32" cy="50" cx="50">
        <animateTransform values="0 50 50;360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1.6666666666666667s" type="rotate" attributeName="transform"></animateTransform>
      </circle>
        <circle stroke-linecap="round" fill="none" stroke-dashoffset="36.12831551628262" stroke-dasharray="36.12831551628262 36.12831551628262" stroke="#f8b26a" stroke-width="8" r="23" cy="50" cx="50">
          <animateTransform values="0 50 50;-360 50 50" keyTimes="0;1" repeatCount="indefinite" dur="1.6666666666666667s" type="rotate" attributeName="transform"></animateTransform>
        </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
    </div>

    <div class="passwd" v-if="!isSuccess">
      <div class="container my-5" :class="{'op-60': isLoading}">
        <div class="row justify-content-center">
          <h1 class="mb-3">Доступ ограничен паролем</h1>
          <div>
            <label for="password" class="form-label">Пароль:</label>
            <div class="d-flex">
              <input v-model="password" :type="displayPassword ? 'text' : 'password'" class="form-control" autofocus id="password" name="password" required>
              <span @click.prevent="displayPassword = !displayPassword" class="btn btn-warning">
                <img class="eye" :src="`/assets/${displayPassword ? 'eye' : 'hidden'}.png`" alt="">
              </span>
            </div>
          </div>
          <div class="mt-4">
            <button class="btn btn-secondary" :disabled="!password" @click="tryAuth">
              Авторизация
            </button>
          </div>
        </div>
      </div>
    </div>

    <wb-form v-if="isSuccess && !isLoading "/>

  </div>
</template>

<script setup lang="ts">
import WbForm from "@/components/wb-form.vue";
import {onMounted, ref} from "vue";

const passwd = localStorage.getItem("passwd");
const password = ref<string>(passwd || '');
const isLoading = ref<boolean>(false);
const isSuccess = ref<boolean>(false);
const displayPassword = ref<boolean>(false);

onMounted(() => {
  tryAuth();
})

const tryAuth = async () => {
  if(!password.value){
    return false;
  }
  isLoading.value = true;
  try{
    const formData = new FormData();
    formData.append("password", password.value);
    formData.append("department", import.meta.env.VITE_DIRECTION_CODE)
    const res = await fetch(import.meta.env.VITE_API_URL + '/api/report/v1.0/try-auth', {
      method: 'POST',
      body: formData
    });
    const data =  await res.json();
    isLoading.value = false;
    if(res.status != 200){
      if(data.message){
        alert(data.message);
      }
      else{
        alert('Не удалось отправить запрос (' + res.status + ')');
      }
      return;
    }
    else{
      localStorage.setItem('passwd', password.value);
      isSuccess.value = true;
      isLoading.value = false;
    }
  }
  catch (e){
    alert('Неверный пароль');
  }
  finally {
    isLoading.value = false;
  }
}

</script>

<style lang="scss" scoped>
.loading-outer{
  position: absolute;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
.passwd{
  .eye{
    width: 20px;
    height: 30px;
    object-fit: contain;
  }
}
.op-60{
  opacity: 60%;
}
</style>